services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:8001"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/src
    networks:
      - backend
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: "django_cont"
    expose:
      - "8001"
    command: sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8001 --reload --reload"
    env_file:
      - ./src/.env
    volumes:
      - ./src:/src
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mysql:9.0
    container_name: "db"
    restart: always
    env_file:
      - ./src/.env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_name
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  mysql_data:
